#pragma once
#include "ve_reg_flavor.h"

// clang-format off

#define TEXTRECORDS(MACRO) \
	MACRO(INV, NUMERIC, "AC_OUT_I", AC_OUT_CURRENT) \
	MACRO(INV, NUMERIC, "AC_OUT_S", AC_OUT_APPARENT_POWER) \
	MACRO(INV, NUMERIC, "AC_OUT_V", AC_OUT_VOLTAGE) \
	MACRO(ANY, BITMASK, "AR", ALARM_REASON) \
	MACRO(BMV, BOOLEAN, "Alarm", ALARM_BUZZER) \
	MACRO(ANY, ENUM, "CS", DEVICE_STATE) \
	MACRO(CHG, ENUM, "ERR", CHR_ERROR_CODE) \
	MACRO(ANY, STRING, "FW", APP_VER) \
	MACRO(ANY, STRING, "FWE", APP_VER) \
	MACRO(MPPT, NUMERIC, "H19", USER_YIELD) \
	MACRO(MPPT, NUMERIC, "H20", YIELD_TODAY) \
	MACRO(MPPT, NUMERIC, "H21", MAXIMUM_POWER_TODAY) \
	MACRO(MPPT, NUMERIC, "H22", YIELD_YESTERDAY) \
	MACRO(MPPT, NUMERIC, "H23", MAXIMUM_POWER_YESTERDAY) \
	MACRO(ANY, NUMERIC, "I", DC_CHANNEL1_CURRENT) \
	MACRO(MPPT, NUMERIC, "IL", LOAD_CURRENT) \
	MACRO(MPPT, BOOLEAN, "LOAD", LOAD_OUTPUT_STATE) \
	MACRO(ANY, ENUM, "MODE", DEVICE_MODE) \
	MACRO(BMV71, STRING, "MON", DC_MONITOR_MODE) \
	MACRO(MPPT, ENUM, "MPPT", MPPT_TRACKER_MODE) \
	MACRO(ANY, BITMASK, "OR", DEVICE_OFF_REASON_2) \
	MACRO(BMV, NUMERIC, "P", DC_CHANNEL1_POWER) \
	MACRO(ANY, UNKNOWN, "PID", PRODUCT_ID) \
	MACRO(MPPT, NUMERIC, "PPV", PANEL_POWER) \
	MACRO(ANY, BOOLEAN, "Relay", RELAY_CONTROL) \
	MACRO(ANY, STRING, "SER#", SERIAL_NUMBER) \
	MACRO(BMV, NUMERIC, "SOC", SOC) \
	MACRO(BMV, NUMERIC, "T", BAT_TEMPERATURE) \
	MACRO(BMV, NUMERIC, "TTG", TTG) \
	MACRO(ANY, NUMERIC, "V", DC_CHANNEL1_VOLTAGE) \
	MACRO(MPPT, NUMERIC, "VPV", PANEL_VOLTAGE) \
	MACRO(INV, BITMASK, "WARN", WARNING_REASON)

// clang-format on