# This file is used as a template for automatic generation of 'flavor' sample configurations.

external_components:
  # source: github://krahabb/esphome # development repo
  source: github://krahabb/esphome-victron-vedirect

uart:
  - id: uart_0
    tx_pin: GPIO4
    rx_pin: GPIO5
    baud_rate: 19200
    rx_buffer_size: 256

m3_vedirect:
  - id: vedirect_0
    uart_id: uart_0
    name: "Victron"
    flavor: [MPPT]
    textframe:
      auto_create_entities: false
    hexframe:
      auto_create_entities: false
      ping_timeout: 2min

binary_sensor:
  - platform: m3_vedirect
    vedirect_id: vedirect_0
    vedirect_entities:
      - register: SOLAR_ACTIVITY
        name: "SOLAR_ACTIVITY"
      - register: LOAD_OUTPUT_STATE
        name: "LOAD_OUTPUT_STATE"

number:
  - platform: m3_vedirect
    vedirect_id: vedirect_0
    vedirect_entities:
      - register: VOLTAGE_COMPENSATION
        name: "VOLTAGE_COMPENSATION"
      - register: BAT_LOW_TEMP_LEVEL
        name: "BAT_LOW_TEMP_LEVEL"
      - register: REBULK_VOLTAGE_OFFSET
        name: "REBULK_VOLTAGE_OFFSET"
      - register: EQUALISATION_DURATION
        name: "EQUALISATION_DURATION"
      - register: EQUALISATION_CURRENT_LEVEL
        name: "EQUALISATION_CURRENT_LEVEL"
      - register: LOW_TEMP_CHARGE_CURRENT
        name: "LOW_TEMP_CHARGE_CURRENT"
      - register: BAT_MAX_CURRENT
        name: "BAT_MAX_CURRENT"
      - register: BAT_TEMPERATURE_COMPENSATION
        name: "BAT_TEMPERATURE_COMPENSATION"
      - register: BAT_EQUALISATION_VOLTAGE
        name: "BAT_EQUALISATION_VOLTAGE"
      - register: BAT_FLOAT_VOLTAGE
        name: "BAT_FLOAT_VOLTAGE"
      - register: BAT_ABSORPTION_VOLTAGE
        name: "BAT_ABSORPTION_VOLTAGE"
      - register: BAT_ABSORPTION_LIMIT
        name: "BAT_ABSORPTION_LIMIT"
      - register: BAT_BULK_LIMIT
        name: "BAT_BULK_LIMIT"
      - register: AUTOMATIC_EQUALISATION_MODE
        name: "AUTOMATIC_EQUALISATION_MODE"

select:
  - platform: m3_vedirect
    vedirect_id: vedirect_0
    vedirect_entities:
      - register: DEVICE_MODE
        name: "DEVICE_MODE"
      - register: RELAY_MODE
        name: "RELAY_MODE"
      - register: BAT_VOLTAGE_SETTING
        name: "BAT_VOLTAGE_SETTING"
      - register: BAT_TYPE
        name: "BAT_TYPE"

sensor:
  - platform: m3_vedirect
    vedirect_id: vedirect_0
    vedirect_entities:
      - register: TIME_OF_DAY
        name: "TIME_OF_DAY"
      - register: DC_CHANNEL1_VOLTAGE
        name: "DC_CHANNEL1_VOLTAGE"
      - register: DC_CHANNEL1_CURRENT
        name: "DC_CHANNEL1_CURRENT"
      - register: LOAD_CURRENT
        name: "LOAD_CURRENT"
      - register: PANEL_MAXIMUM_VOLTAGE
        name: "PANEL_MAXIMUM_VOLTAGE"
      - register: PANEL_VOLTAGE
        name: "PANEL_VOLTAGE"
      - register: PANEL_POWER
        name: "PANEL_POWER"
      - register: PANEL_CURRENT
        name: "PANEL_CURRENT"
      - register: MAXIMUM_POWER_YESTERDAY
        name: "MAXIMUM_POWER_YESTERDAY"
      - register: YIELD_YESTERDAY
        name: "YIELD_YESTERDAY"
      - register: MAXIMUM_POWER_TODAY
        name: "MAXIMUM_POWER_TODAY"
      - register: YIELD_TODAY
        name: "YIELD_TODAY"
      - register: CHARGER_VOLTAGE
        name: "CHARGER_VOLTAGE"
      - register: CHARGER_CURRENT
        name: "CHARGER_CURRENT"
      - register: CHR_INTERNAL_TEMPERATURE
        name: "CHR_INTERNAL_TEMPERATURE"
      - register: USER_YIELD
        name: "USER_YIELD"
      - register: SYSTEM_YIELD
        name: "SYSTEM_YIELD"
      - register: BAT_TEMPERATURE
        name: "BAT_TEMPERATURE"
      - register: BAT_VOLTAGE
        name: "BAT_VOLTAGE"

switch:
  - platform: m3_vedirect
    vedirect_id: vedirect_0
    vedirect_entities:
      - register: RELAY_CONTROL
        name: "RELAY_CONTROL"
      - register: AUTO_EQUALISE_STOP_ON_VOLTAGE
        name: "AUTO_EQUALISE_STOP_ON_VOLTAGE"
      - register: BMS_PRESENT
        name: "BMS_PRESENT"
      - register: ADAPTIVE_MODE
        name: "ADAPTIVE_MODE"

text_sensor:
  - platform: m3_vedirect
    vedirect_id: vedirect_0
    vedirect_entities:
      - register: BLE_MODE
        name: "BLE_MODE"
      - register: PRODUCT_ID
        name: "PRODUCT_ID"
      - register: APP_VER
        name: "APP_VER"
      - register: SERIAL_NUMBER
        name: "SERIAL_NUMBER"
      - register: MODEL_NAME
        name: "MODEL_NAME"
      - register: CAPABILITIES
        name: "CAPABILITIES"
      - register: CAPABILITIES_BLE
        name: "CAPABILITIES_BLE"
      - register: DEVICE_STATE
        name: "DEVICE_STATE"
      - register: DEVICE_OFF_REASON
        name: "DEVICE_OFF_REASON"
      - register: DEVICE_OFF_REASON_2
        name: "DEVICE_OFF_REASON_2"
      - register: CHARGER_DEVICE_STATE
        name: "CHARGER_DEVICE_STATE"
      - register: WARNING_REASON
        name: "WARNING_REASON"
      - register: ALARM_REASON
        name: "ALARM_REASON"
      - register: MPPT_TRACKER_MODE
        name: "MPPT_TRACKER_MODE"
      - register: CHR_ERROR_CODE
        name: "CHR_ERROR_CODE"
