# This file is used as a template for automatic generation of 'flavor' sample configurations.

# Substitute with your platform configuration of choice
<<: !include _m3_vedirect_platform_config.yaml

external_components:
  # source: github://krahabb/esphome # development repo
  source: github://krahabb/esphome-victron-vedirect

uart:
  - id: uart_0
    tx_pin: GPIO4
    rx_pin: GPIO5
    baud_rate: 19200
    rx_buffer_size: 256

m3_vedirect:
  - id: vedirect_0
    uart_id: uart_0
    name: "Victron"
    flavor: [INV]
    textframe:
      auto_create_entities: false
    hexframe:
      auto_create_entities: false
      ping_timeout: 2min

number:
  - platform: m3_vedirect
    vedirect_id: vedirect_0
    vedirect_entities:
      - register: AC_OUT_VOLTAGE_SETPOINT
        name: "AC_OUT_VOLTAGE_SETPOINT"
      - register: ALARM_LOW_VOLTAGE_SET
        name: "ALARM_LOW_VOLTAGE_SET"
      - register: ALARM_LOW_VOLTAGE_CLEAR
        name: "ALARM_LOW_VOLTAGE_CLEAR"
      - register: SHUTDOWN_LOW_VOLTAGE_SET
        name: "SHUTDOWN_LOW_VOLTAGE_SET"

select:
  - platform: m3_vedirect
    vedirect_id: vedirect_0
    vedirect_entities:
      - register: DEVICE_MODE
        name: "DEVICE_MODE"
      - register: RELAY_MODE
        name: "RELAY_MODE"

sensor:
  - platform: m3_vedirect
    vedirect_id: vedirect_0
    vedirect_entities:
      - register: AC_OUT_VOLTAGE
        name: "AC_OUT_VOLTAGE"
      - register: AC_OUT_CURRENT
        name: "AC_OUT_CURRENT"
      - register: AC_OUT_APPARENT_POWER
        name: "AC_OUT_APPARENT_POWER"
      - register: VOLTAGE_RANGE_MIN
        name: "VOLTAGE_RANGE_MIN"
      - register: VOLTAGE_RANGE_MAX
        name: "VOLTAGE_RANGE_MAX"
      - register: DC_CHANNEL1_VOLTAGE
        name: "DC_CHANNEL1_VOLTAGE"
      - register: DC_CHANNEL1_CURRENT
        name: "DC_CHANNEL1_CURRENT"
      - register: BAT_TEMPERATURE
        name: "BAT_TEMPERATURE"

switch:
  - platform: m3_vedirect
    vedirect_id: vedirect_0
    vedirect_entities:
      - register: RELAY_CONTROL
        name: "RELAY_CONTROL"

text_sensor:
  - platform: m3_vedirect
    vedirect_id: vedirect_0
    vedirect_entities:
      - register: BLE_MODE
        name: "BLE_MODE"
      - register: PRODUCT_ID
        name: "PRODUCT_ID"
      - register: APP_VER
        name: "APP_VER"
      - register: SERIAL_NUMBER
        name: "SERIAL_NUMBER"
      - register: MODEL_NAME
        name: "MODEL_NAME"
      - register: CAPABILITIES
        name: "CAPABILITIES"
      - register: CAPABILITIES_BLE
        name: "CAPABILITIES_BLE"
      - register: DEVICE_STATE
        name: "DEVICE_STATE"
      - register: DEVICE_OFF_REASON
        name: "DEVICE_OFF_REASON"
      - register: DEVICE_OFF_REASON_2
        name: "DEVICE_OFF_REASON_2"
      - register: INVERTER_DEVICE_STATE
        name: "INVERTER_DEVICE_STATE"
      - register: WARNING_REASON
        name: "WARNING_REASON"
      - register: ALARM_REASON
        name: "ALARM_REASON"
